### ISSUE TITLE
Upgrade to tomcat 8.5

### ISSUE THREAD

**Issue by banzo** [cetic/ansible-role-alfresco#3]
Currently 7.0.61

**Comment by alexnuttinck** [comment]
The alfresco ansible role now uses version 8.5.31 of tomcat.
The setup part of tomcat has now its own ansible role, available at: https://github.com/cetic/ansible-role-tomcat8.5 
This ansible role is also available on ansible galaxy; https://galaxy.ansible.com/cetic/tomcat/
