### ISSUE TITLE
"inventory_path" error

### ISSUE THREAD

**Issue by tiurlumbangaol** [cetic/ansible-role-alfresco#4]
hi,

thanks for the script. it would benefit so many people.

i download it, and try to run "vagrant up", but there is errror : 
==> controller: Running provisioner: ansible_local...
`inventory_path` does not exist on the guest: /vagrant/tests/hosts

i check on guest vm, there is no "/vagrant/tests/hosts" file

please help...

**Comment by alexnuttinck** [comment]
Hi,

Thanks for your report,

It is corrected now, my .gitignore was ignoring the hosts file.

I warn you that the vagrant is used for testing purposes.
You will need to add an ansible role for the database in your own playbook. (See the requirements).

**Comment by tiurlumbangaol** [comment]
hi thanks, the previous error is gone now...

but i got another error : 

==> controller: Running provisioner: ansible_local...
    controller: Installing Ansible...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sudo rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-`rpm -E %dist | sed -n 's/.*el\([0-9]\).*/\1/p'`.noarch.rpm

Stdout from the command:



Stderr from the command:

curl: (6) Could not resolve host: dl.fedoraproject.org; Unknown error
error: skipping https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm - transfer failed
----------

I think the network can't connect to internet. I need to change the network to become public, then the error is vanished.

do you think, we need to change it in git to become public?

btw, any plan to release ansible for Alfresco 6 version?

**Comment by alexnuttinck** [comment]
Hi,

I don't think so, change to public from private network won't solve this problem. It seems to be related to a network error. It can overcome some times. But, tell me if the problem overcomes again.

There is no plan to release for Alfresco 6, at this time. But feel free to contibute by making a pull request.
